### PR TITLE
Prepare a new major version

### PR DESCRIPTION
**Pull request by vbuch**
I'm doing more than one thing at a time. While this is WIP, I'm logging changes in the [CHANGELOG](CHANGELOG.md). The main feature is the helper to sign a non-pdfkit created document as per #22

### CODE REVIEW

**Comment by vbuch** [comment]
@maldimirov if/when you have time, could you give the code a glance? If/when you have more time, you could even modify what you don't like :) I'm not asking @samaleksov because he has some other coding snippets to do...

**Comment by MohammedEssehemy** [comment]
@vbuch could we list what's missing in PDF signature verification instead of removing this functionality from the library?

**Comment by vbuch** [comment]
@MohammedEssehemy there were more than one reasons when i descided that. 1. I had a real usecase when I was giving it an invalid signed doc and it reported it as valid. It was i think a malformed pdf that didnt have the appropriate links for the elements. But since the byte range is extracted without reading the file structure, it was reported as valid.
2. I am pretty sure people will rarely need both signing and verification in the same project. If youbsplit your services well, you will have separate services for those two actions.
3. The two processes have totally different dependencies. 
4. I don't have the time to deal with signing alone. I totally cannot support verification. 

As I already wrote, the best would be if you created a separate package for that. I would be more than happy to help extract some helpers out into a shared lib so you dont have to rewrite or copy/paste them. Also I would be happy to use it in the testing of this repo. I also think it can be used in the tests of node-forge once available to verify the detached signing.

**Comment by MohammedEssehemy** [comment]
@vbuch I'll work with my team on separating the package and will inform you once the package is ready, and will tell you about the helpers we need.

**Comment by MohammedEssehemy** [comment]
@vbuch we have released version 0.1.0 from the library with multiple bug fixes.
it's called [verrify-pdf](https://github.com/ninja-labs-tech/verify-pdf)
@Tarek-Essam

**Pull request merged**
