### PR TITLE
Add support for overriding signature SubFilter value

### PR DESCRIPTION
**Pull request by dhensby**
To confirm to the PAdES standard PDF signatures need to have the `SubFilter` value of `ETSI.CAdES.detached` not `adbe.pkcs7.detached`

> l) The Signature Dictionary shall contain a value of ETSI.CAdES.detached for the key SubFilter. [1]

This PR allows consumers of this library to define the SubFilter as required

---

[1] https://www.etsi.org/deliver/etsi_en/319100_319199/31914201/01.01.01_60/en_31914201v010101p.pdf

### CODE REVIEW

**Review by vbuch — CHANGES_REQUESTED** [review]
Great! Thank you!

Can you name it `SubFilter` or `subFilter`? Because sigType is too generic and might lead to some mismatches in the future. Or whatever naming you prefer that describes what this value is going to be used for.

Could you switch from plan string to constants? So we can make sure there are no typos causing bug reports, then people investigating typos, etc.

Additionally: Please check the readme. Not sure if this has a good place to be added there. Just check what makes sense. The readme is quite general and examples are done in code instead so I think there shouldn't be a need for change there. Just check.

**Comment by dhensby** [comment]
1. I've added the constants for the different signature SubFilter values as per the PDF docs (https://www.adobe.com/devnet-docs/etk_deprecated/tools/DigSig/Acrobat_DigitalSignatures_in_PDF.pdf) and the ETSI PAdES value.
2. I've had to export the constants as they aren't actually available to consumers (that I could see) to allow the constants to be used.
3. I've added some basic readme docs; I think PAdES support stuff is worth mentioning in the docs.

**Review by vbuch — APPROVED** [review]

**Comment by vbuch** [comment]
@dhensby could you please resolve the conflicts here so I can hit the merge button. Will try to find the time to also fix the CI at some point, but have too much on my head and willing to reduce the easy ones: Like this one that was good to be merged at some point.

**Comment by dhensby** [comment]
done

**Pull request merged**
