### PR TITLE
Duplicate startxref in some PDFs

### PR DESCRIPTION
**Pull request by mgyugcha**
In some PDFs the `/Root` is the last key of the trailer so the search should be with `/` and also with `>`.

image

### Explanation
If this is ignored the rootSlice has unwanted values:

**Expected:**
image

**Obtained:**
image

This causes the PDF to have an additional startxref:

image

### CODE REVIEW

**Comment by therpobinski** [comment]
Thanks, with this 'extraction request' this [isuue](https://github.com/vbuch/node-signpdf/issues/75) is solved.
We have been working hard with @mgyugcha to fix it, and everything has been satisfactory.
Thanks @mgyugcha and congratulations. It is a great contribution.

**Comment by vbuch** [comment]
By reading the code I don't understand what this commit fixes. If I read through the issue, I do. If you write a test that covers that, it will be obvious when reading the code and code coverage will not be lowered, hence @coveralls won't complain. Please take the time to write a test so this can be merged.

**Comment by mgyugcha** [comment]
Hi @vbuch, please check the test I did.

Without this update the new trailer contains two `startxref` when generating the placeholder, as shown in the picture:

image

**Comment by vbuch** [comment]
Released in [1.3.0](https://github.com/vbuch/node-signpdf/releases/tag/v1.3.0)

**Pull request merged**
