### PR TITLE
messageDigest to A1 Brazil certificate

### PR DESCRIPTION
**Pull request by joseAAlexandre**

### CODE REVIEW

**Comment by vbuch** [comment]
@joseAAlexandre, please cover that with a test. Ensure the order is maintained. Why this is important:
1. We'll make sure the next contributor doesn't overwrite it back;
2. We'll make sure we have a documented reason in the test;

**Comment by joseAAlexandre** [comment]
I have no time this monthy. As soon as possible I will check the tests

**Comment by joseAAlexandre** [comment]
Is it ok if you merge this in another branch so i can import temporarily?

**Comment by vbuch** [comment]
@joseAAlexandre you can build and import from your fork. https://docs.npmjs.com/cli/v8/configuring-npm/package-json#git-urls-as-dependencies

**Pull request closed without merging**
