### PR TITLE
Deprecated extractSignature as it was never public-ready.

### PR DESCRIPTION
**Pull request by vbuch**
Copied it in internal-utils to be used in tests. Will remove from `utils` in a next major release (#206)

### CODE REVIEW

**Review by MindFreeze — APPROVED** [review]

**Comment by dhensby** [comment]
Is it worth making use of [`util.deprecate()`](https://nodejs.org/api/util.html#utildeprecatefn-msg-code) to properly mark the function as deprecated?

**Comment by vbuch** [comment]
> Is it worth making use of [`util.deprecate()`](https://nodejs.org/api/util.html#utildeprecatefn-msg-code) to properly mark the function as deprecated?

✅

**Comment by dhensby** [comment]
I'm going through the upgrade process/refactor of my project that uses pdfsign and I've just noticed that I'm using `extractSignature` as a helper in our tests - essentially just to assert that there is indeed a signature in the PDF we've created. This is especially helpful when writing a custom signer and you want to assert that a signature was indeed added.

Is there a better way to do that?

**Comment by vbuch** [comment]
The best I can think of would be to use an external library that deals with signature verification and exports such a utility. [This one](https://github.com/ninja-labs-tech/verify-pdf) used to be part of node-signpdf some 5 years ago and is the only one I know.  Finding such a library would actualy render our own extractSignature useless.

**Comment by vbuch** [comment]
With the above in mind I'm closing this. I understand that the util may come handy to some. What I will do instead is create an adequate wording around it that clearly states this is not public-ready code.

**Pull request closed without merging**
